### ISSUE TITLE
Request for CONTRIBUTING.md

### ISSUE THREAD

**Issue by a-galishnikov** [chivaler/ATG-Toolkit#7]
Hello,

This issue is just a request for CONTRIBUTING.md file to make contributing to this plugin more obvious.
Our team (Letoile - www.letu.ru/www.letu.ua) has few developers interested in adding new features to ATG-Toolkit. 

Couldn't find any contacts to reach out in a more comfortable way.
Please get back to me if you are interested in involving us as contributors.

Regards,
Anton G.

skype: anton_galishnikov, 
telegram: +79271189288, 
email: galishnikovaa@gmail.com

**Comment by chivaler** [comment]
have a look at MR #9
